/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Alumno;
import Entidades.Materias;
import accesoDatos.AlumnoData;
import accesoDatos.MateriaData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author elihe
 */
public class FormularioMateria extends javax.swing.JInternalFrame {
     private MateriaData matData=new MateriaData();
    private Materias materiaActual=null;
    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLMateria = new javax.swing.JLabel();
        JLCodigo = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLAnio = new javax.swing.JLabel();
        JLEStado = new javax.swing.JLabel();
        JTCodigo = new javax.swing.JTextField();
        JTNombre = new javax.swing.JTextField();
        JTAnio = new javax.swing.JTextField();
        JBBuscar = new javax.swing.JButton();
        JBNuevo = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBGuardar = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        JREstado = new javax.swing.JRadioButton();

        JLMateria.setText("Materia");

        JLCodigo.setText("Codigo:");

        JLNombre.setText("Nombre:");

        JLAnio.setText("Año:");

        JLEStado.setText("Estado:");

        JTAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTAnioActionPerformed(evt);
            }
        });

        JBBuscar.setText("Buscar");
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        JBNuevo.setText("Nuevo");
        JBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNuevoActionPerformed(evt);
            }
        });

        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        JBGuardar.setText("Guardar");
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(JLMateria))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLAnio)
                                        .addComponent(JLEStado))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JREstado)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLNombre)
                                        .addComponent(JLCodigo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(JTNombre))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBSalir)
                    .addComponent(JBBuscar))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLMateria)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCodigo)
                    .addComponent(JTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBBuscar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(JTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLAnio)
                    .addComponent(JTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEStado)
                    .addComponent(JREstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBNuevo)
                    .addComponent(JBEliminar)
                    .addComponent(JBGuardar)
                    .addComponent(JBSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        // TODO add your handling code here:
        if(materiaActual!=null){
            matData.eliminarMateria(materiaActual.getAnio());
            materiaActual=null;
            limpiarCampos();
        
        }else{
            JOptionPane.showMessageDialog(this,"No hay materia seleccionada");
        }
     
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JTAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAnioActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Integer codigo=Integer.parseInt(JTCodigo.getText());
//            
              materiaActual=matData.buscarM(codigo);
            if(materiaActual!=null){
                JTNombre.setText(materiaActual.getNombre());
                JREstado.setSelected(materiaActual.isEstado());
                JTAnio.setText((Integer.toString(materiaActual.getAnio())));
                
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar un número válido");
        }
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void JBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        materiaActual=null;
    }//GEN-LAST:event_JBNuevoActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        // TODO add your handling code here:
        try{
            Integer codigo=Integer.parseInt(JTCodigo.getText());
            String nombre=JTNombre.getText();
            Integer anio=Integer.parseInt(JTAnio.getText());
            if(nombre.isEmpty()){
             JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
             return;
            }
            
            Boolean estado=JREstado.isSelected();
            if(materiaActual==null){
                materiaActual=new Materias(codigo,nombre,anio,estado);
                matData.guardarMateria(materiaActual);
            }else{
                materiaActual.setIdMateria(codigo);
                materiaActual.setNombre(nombre);
                materiaActual.setAnio(anio);
                
                matData.modificarMateria(materiaActual);
                
            }
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar un Código válido");
        }
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_JBSalirActionPerformed
private void limpiarCampos(){
        JTCodigo.setText("");
        JTNombre.setText("");
        JTAnio.setText("");
        JREstado.setSelected(true);
}
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBNuevo;
    private javax.swing.JButton JBSalir;
    private javax.swing.JLabel JLAnio;
    private javax.swing.JLabel JLCodigo;
    private javax.swing.JLabel JLEStado;
    private javax.swing.JLabel JLMateria;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JRadioButton JREstado;
    private javax.swing.JTextField JTAnio;
    private javax.swing.JTextField JTCodigo;
    private javax.swing.JTextField JTNombre;
    // End of variables declaration//GEN-END:variables
}
