/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;

/**
 *
 * @author elihe
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(500, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon(getClass().getResource("/Recursos/ulp.jpeg"));
        Image miFondo=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miFondo,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar2 = new javax.swing.JMenuBar();
        JMalumno = new javax.swing.JMenu();
        JMIformularioalum = new javax.swing.JMenuItem();
        JMmateria = new javax.swing.JMenu();
        JMIformulariomat = new javax.swing.JMenuItem();
        JMadministracion = new javax.swing.JMenu();
        JMIinscrpciones = new javax.swing.JMenuItem();
        JMInotas = new javax.swing.JMenuItem();
        JMconsultas = new javax.swing.JMenu();
        JMIalumnosxmat = new javax.swing.JMenuItem();
        JMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        JMalumno.setText("Alumno");

        JMIformularioalum.setText("Formulario de Alumno");
        JMIformularioalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformularioalumActionPerformed(evt);
            }
        });
        JMalumno.add(JMIformularioalum);

        jMenuBar2.add(JMalumno);

        JMmateria.setText("Materia");

        JMIformulariomat.setText("Formulario de Materia");
        JMIformulariomat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformulariomatActionPerformed(evt);
            }
        });
        JMmateria.add(JMIformulariomat);

        jMenuBar2.add(JMmateria);

        JMadministracion.setText("Administración");

        JMIinscrpciones.setText("Manejo de Inscripciones");
        JMIinscrpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIinscrpcionesActionPerformed(evt);
            }
        });
        JMadministracion.add(JMIinscrpciones);

        JMInotas.setText("Manejo de notas");
        JMInotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMInotasActionPerformed(evt);
            }
        });
        JMadministracion.add(JMInotas);

        jMenuBar2.add(JMadministracion);

        JMconsultas.setText("Consultas");

        JMIalumnosxmat.setText("Alumnos por Materia");
        JMIalumnosxmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIalumnosxmatActionPerformed(evt);
            }
        });
        JMconsultas.add(JMIalumnosxmat);

        jMenuBar2.add(JMconsultas);

        JMsalir.setText("Salir");
        jMenuBar2.add(JMsalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIinscrpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIinscrpcionesActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         escritorio.repaint();
         FormularioInscripcion inscripcion = new FormularioInscripcion();
         inscripcion.setVisible(true);
         inscripcion.getContentPane().setBackground(new Color(68, 167, 132));
         escritorio.add(inscripcion);
    }//GEN-LAST:event_JMIinscrpcionesActionPerformed

    private void JMIformularioalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformularioalumActionPerformed
         // TODO add your handling code here:
         escritorio.removeAll();
         escritorio.repaint();
         FormularioAlumno alumno = new FormularioAlumno();
         alumno.setVisible(true);
         alumno.getContentPane().setBackground(new Color(68, 167, 132));
         escritorio.add(alumno);
         
    }//GEN-LAST:event_JMIformularioalumActionPerformed

    private void JMIformulariomatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformulariomatActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         escritorio.repaint();
         FormularioMateria materia = new FormularioMateria();
         materia.setVisible(true);
         materia.getContentPane().setBackground(new Color(68, 167, 132));
         escritorio.add(materia);
    }//GEN-LAST:event_JMIformulariomatActionPerformed

    private void JMInotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMInotasActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         escritorio.repaint();
         FormularioNotas nota = new FormularioNotas();
         nota.setVisible(true);
         nota.getContentPane().setBackground(new Color(68, 167, 132));
         escritorio.add(nota);
    }//GEN-LAST:event_JMInotasActionPerformed

    private void JMIalumnosxmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIalumnosxmatActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         escritorio.repaint();
         AlumnosPorMateria alumnoxmat = new AlumnosPorMateria();
         alumnoxmat.setVisible(true);
         alumnoxmat.getContentPane().setBackground(new Color(68, 167, 132));
         escritorio.add(alumnoxmat);
    }//GEN-LAST:event_JMIalumnosxmatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIalumnosxmat;
    private javax.swing.JMenuItem JMIformularioalum;
    private javax.swing.JMenuItem JMIformulariomat;
    private javax.swing.JMenuItem JMIinscrpciones;
    private javax.swing.JMenuItem JMInotas;
    private javax.swing.JMenu JMadministracion;
    private javax.swing.JMenu JMalumno;
    private javax.swing.JMenu JMconsultas;
    private javax.swing.JMenu JMmateria;
    private javax.swing.JMenu JMsalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
